version: '3.9'
services:
  api:
    build: .
    container_name: api_logix
    tty: true
    env_file:
      - .env
    volumes:
      - ./app:/app
      - sqlhosts /opt/IBM/Informix_Client-SDK/etc/sqlhosts
    ports:
      - 5000:5000
    # command: python3 app.py
  db:
        build: ./DB
        tty: true # Needed to ensure container doesn't self terminate
        environment:
            LICENSE: accept
            DB_PASSWORD: 123456
        privileged: true
        ports:
            - "9088:9088"
            - "9089:9089"
            - "27017:27017"
            - "27018:27018"
            - "27883:27883"
networks:
  api:
    driver: bridge